language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 **/*.py
  - coverage run --source=polls manage.py test
  - coverage report

after_script:
  - curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
  
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-991134317384"
  on:
    branch: main

